# Generated by Django 4.2.20 on 2025-10-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('foto', models.ImageField(upload_to='fotos_reus/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('num_processo', models.CharField(max_length=20, null=True)),
                ('endereco', models.CharField(default='SOME STRING', max_length=200, null=True)),
                ('data_expiracao', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateTimeField(auto_now_add=True)),
                ('reu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.reu')),
            ],
        ),
    ]
