# Generated by Django 4.2.20 on 2025-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data_presenca',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
