# Generated by Django 4.2.20 on 2025-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reu',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='reu',
            name='num_processo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
