# Generated by Django 4.2.20 on 2025-07-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_presenca_data_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='num_processo',
            field=models.CharField(default='000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='000000', max_length=12, null=True),
        ),
    ]
